// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdktcvxuymbsyaevwjrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBka3Rjdnh1eW1ic3lhZXZ3anJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzY4MDcsImV4cCI6MjA2NjYxMjgwN30.6lgEBdkBnvrDIgWh3JKambXcCtFIKTcodHiEf6uA4wY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);